apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-user: {{ .Values.auth.auth | quote }}
  mysql-password: {{ .Values.auth.password | quote }}
  mysql-root-password: {{ .Values.auth.rootPassword | quote }}
  mysql-database: {{ .Values.auth.database | quote }}
