apiVersion: v2
name: ckbox-stack
description: CKBox On-Premises stack installation

type: application
version: 1.0.0
appVersion: "latest"

dependencies:
  - name: ckbox
    version: "1.0.0"
    repository: "file://../ckbox"
  - name: mysql
    condition: mysql.enabled
    version: "1.0.0"
    repository: "file://../misc/mysql"
  - name: redis
    condition: redis.enabled
    version: "1.0.0"
    repository: "file://../misc/redis"
