apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckbox.secretName" . }}
  labels:
    {{- include "ckbox.labels" . | nindent 4 }}
{{- with .Values.secret.data }}
stringData:

  {{- toYaml . | nindent 2 }}
{{- end }}
