apiVersion: v1
kind: Service
metadata:
  name: ckbox
  labels:
    app.kubernetes.io/name: ckbox
    app.kubernetes.io/instance: ckbox
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: ckbox
    app.kubernetes.io/instance: ckbox

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckbox
  labels:
    app.kubernetes.io/name: ckbox
    app.kubernetes.io/instance: ckbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: ckbox
      app.kubernetes.io/instance: ckbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ckbox
        app.kubernetes.io/instance: ckbox
    spec:
      imagePullSecrets:
        - name: docker-cke-cs-com
      securityContext: {}
      containers:
        - name: ckbox
          securityContext: {}
          image: "docker.cke-cs.com/cs:latest"
          imagePullPolicy: IfNotPresent
          command:
            - "node"
          args:
            - "--tls-min-v1.0"
            - "./app/dist/index.js"
          ports:
            - name: tcp
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: tcp
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DATABASE_HOST
              value: ""
            - name: DATABASE_PASSWORD
              value: ""
            - name: DATABASE_USER
              value: ""
            - name: ENVIRONMENTS_MANAGEMENT_SECRET_KEY
              value: ""
            - name: LICENSE_KEY
              value: ""
            - name: REDIS_HOST
              value: ""
            - name: STORAGE_DRIVER
              value: ""
            - name: STORAGE_LOCATION
              value: ""
            - name: COLLABORATION_STORAGE_DRIVER
              value: ""
            - name: COLLABORATION_STORAGE_LOCATION
              value: ""

          resources:
            requests:
              cpu: 2000m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 1536Mi
